// <auto-generated />
using System;
using HidroRec.Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HidroRec.Backend.Migrations
{
    [DbContext(typeof(HidroRecDbContext))]
    [Migration("20260331152639_ScaleReadinessIndexesAndConcurrency")]
    partial class ScaleReadinessIndexesAndConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AreaAfetada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("BairroId")
                        .HasColumnType("int");

                    b.Property<string>("Criticidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<string>("OrientacaoResumida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.HasIndex("Ativo", "Criticidade", "BairroId", "DataCriacao")
                        .HasDatabaseName("IX_Alertas_Ativo_Criticidade_Bairro_DataCriacao");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.AlertaReporte", b =>
                {
                    b.Property<Guid>("AlertaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReporteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AlertaId", "ReporteId");

                    b.HasIndex("ReporteId");

                    b.ToTable("AlertasReportes");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntidadeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "DataCriacao")
                        .HasDatabaseName("IX_Auditorias_Usuario_DataCriacao");

                    b.HasIndex("Entidade", "EntidadeId", "DataCriacao")
                        .HasDatabaseName("IX_Auditorias_Entidade_EntidadeId_DataCriacao");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Bairro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RegiaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoId", "Nome")
                        .IsUnique();

                    b.ToTable("Bairros");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.FonteDado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FontesDado");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.HistoricoReporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlteradoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReporteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusAnterior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusNovo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlteradoPorUsuarioId");

                    b.HasIndex("ReporteId", "DataAlteracao")
                        .HasDatabaseName("IX_HistoricosReporte_Reporte_DataAlteracao");

                    b.ToTable("HistoricosReporte");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.IndicadorClimatico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<int>("FonteDadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReferenciaEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("FonteDadoId", "Categoria", "ReferenciaEm")
                        .HasDatabaseName("IX_IndicadoresClimaticos_Fonte_Categoria_Referencia");

                    b.ToTable("IndicadoresClimaticos");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.LogSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Contexto", "DataCriacao")
                        .HasDatabaseName("IX_LogsSistema_Contexto_DataCriacao");

                    b.HasIndex("Nivel", "Evento", "DataCriacao")
                        .HasDatabaseName("IX_LogsSistema_Nivel_Evento_DataCriacao");

                    b.ToTable("LogsSistema");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.PerfilPermissao", b =>
                {
                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.HasKey("PerfilId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("PerfilPermissoes");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permissoes");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Regiao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Regioes");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Reporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BairroId")
                        .HasColumnType("int");

                    b.Property<string>("BairroNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaminhoImagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContatoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoReferencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("NivelAgua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegiaoId")
                        .HasColumnType("int");

                    b.Property<string>("RegiaoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Severidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TipoOcorrencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Excluido", "BairroId", "DataOcorrencia")
                        .HasDatabaseName("IX_Reportes_Bairro_DataOcorrencia");

                    b.HasIndex("Excluido", "RegiaoId", "DataOcorrencia")
                        .HasDatabaseName("IX_Reportes_Regiao_DataOcorrencia");

                    b.HasIndex("Excluido", "UsuarioId", "DataCriacao")
                        .HasDatabaseName("IX_Reportes_Usuario_DataCriacao");

                    b.HasIndex("Excluido", "DataOcorrencia", "Status", "Severidade")
                        .HasDatabaseName("IX_Reportes_DashboardLookup");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PerfilId", "Ativo", "DataCriacao");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Alerta", b =>
                {
                    b.HasOne("HidroRec.Backend.Domain.Entities.Bairro", "Bairro")
                        .WithMany("Alertas")
                        .HasForeignKey("BairroId");

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.AlertaReporte", b =>
                {
                    b.HasOne("HidroRec.Backend.Domain.Entities.Alerta", "Alerta")
                        .WithMany("AlertaReportes")
                        .HasForeignKey("AlertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HidroRec.Backend.Domain.Entities.Reporte", "Reporte")
                        .WithMany("AlertaReportes")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerta");

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("HidroRec.Backend.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Bairro", b =>
                {
                    b.HasOne("HidroRec.Backend.Domain.Entities.Regiao", "Regiao")
                        .WithMany("Bairros")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.HistoricoReporte", b =>
                {
                    b.HasOne("HidroRec.Backend.Domain.Entities.Usuario", "AlteradoPorUsuario")
                        .WithMany()
                        .HasForeignKey("AlteradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HidroRec.Backend.Domain.Entities.Reporte", "Reporte")
                        .WithMany("Historicos")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlteradoPorUsuario");

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.IndicadorClimatico", b =>
                {
                    b.HasOne("HidroRec.Backend.Domain.Entities.FonteDado", "FonteDado")
                        .WithMany("IndicadoresClimaticos")
                        .HasForeignKey("FonteDadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FonteDado");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.PerfilPermissao", b =>
                {
                    b.HasOne("HidroRec.Backend.Domain.Entities.Perfil", "Perfil")
                        .WithMany("PerfilPermissoes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HidroRec.Backend.Domain.Entities.Permissao", "Permissao")
                        .WithMany("PerfilPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Reporte", b =>
                {
                    b.HasOne("HidroRec.Backend.Domain.Entities.Bairro", "Bairro")
                        .WithMany("Reportes")
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HidroRec.Backend.Domain.Entities.Regiao", "Regiao")
                        .WithMany()
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HidroRec.Backend.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Bairro");

                    b.Navigation("Regiao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("HidroRec.Backend.Domain.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Alerta", b =>
                {
                    b.Navigation("AlertaReportes");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Bairro", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.FonteDado", b =>
                {
                    b.Navigation("IndicadoresClimaticos");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("PerfilPermissoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Permissao", b =>
                {
                    b.Navigation("PerfilPermissoes");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Regiao", b =>
                {
                    b.Navigation("Bairros");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Reporte", b =>
                {
                    b.Navigation("AlertaReportes");

                    b.Navigation("Historicos");
                });

            modelBuilder.Entity("HidroRec.Backend.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
